import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { makeUrl, fetcher} from '../src/services'
import {  useState } from 'react'


interface ICharacter {
  name: string
  description:string
  thumbnail: {
    path: string
    extension:string
  }
}
// const fetcher = (...args) => fetch(...args).then(res => res.json())
const Home: NextPage = () => {
  const  [characters, setCharacters] = useState([])
  const [loading, setLoading] = useState(true)
  const init = async (url) =>{ 
   const data =  await fetcher(url)
   setCharacters(data.data.results)
    return data
  }
  if(loading){
    const url = makeUrl()
    init(url)
    setLoading(false)
    
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to MARVEL
        </h1>
        <h2>{loading&&
        loading}</h2>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.grid}>
         {
           characters&&
           characters.map((char:ICharacter,index) =>{
             return (<div key={index} className={styles.card}>
              <h3>{char?.name}</h3>
              <img className={styles.image} src={`${char?.thumbnail.path}.${char?.thumbnail.extension}`} />
              <br/>
              <i>{char?.description}</i>
            </div>) 
           })
         }

         
        </div>
      </main>

      <footer className={styles.footer}>
      <p>marvel comics</p>
      </footer>
    </div>
  )
}

export default Home
